config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: 'home#index'

  resources :books do
    resources :reviews

  end

  resources :authors, only: [:show, :destroy]
  resources :users, only: [:show, :index, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  validates_presence_of :name
  validates_uniqueness_of :name, :case_sensitive => false
  before_save :titleizer

  has_many :book_authors, dependent: :destroy
  has_many :books, through: :book_authors

  def titleizer
    self.name = self.name.titleize
  end

end

app/models/book.rb
class Book < ApplicationRecord
  validates_presence_of :title, :pages, :year
  validates_uniqueness_of :title
  before_save :titleizer

  has_many :book_authors, dependent: :destroy
  has_many :authors, through: :book_authors
  has_many :reviews, dependent: :destroy

  def titleizer
    if self.title
      self.title = self.title.titleize
    end
  end

  def self.all_avg_rating(order)
    books = self.select("books.*, coalesce(avg(reviews.rating), 0) AS avg_rating")
                .left_outer_joins(:reviews)
                .group("books.id")
                .order("avg_rating #{order}")
  end

  def self.highest_rated_books
    books = self.select("books.*, avg(reviews.rating) AS avg_rating").joins(:reviews).group("books.id").order("avg_rating desc").limit(3)
  end

  def self.lowest_rated_books
    books = self.select("books.*, avg(reviews.rating) AS avg_rating").joins(:reviews).group("books.id").order("avg_rating ").limit(3)
  end

  def self.number_of_pages(order)
    self.order("pages #{order}")
  end

  def self.number_of_reviews(order)
    self.select("books.*, coalesce(count(reviews.id),0) AS count").left_outer_joins(:reviews).group(:id).order("count #{order}")
  end

  def self.sort(params)
    if params[:sort] == "asc_rating"
      all_avg_rating("asc")
    elsif params[:sort] == "desc_rating"
      all_avg_rating("desc")
    elsif params[:sort] == "asc_pages"
      number_of_pages("asc")
    elsif params[:sort] == "desc_pages"
      number_of_pages("desc")
    elsif params[:sort] == "asc_reviews"
      number_of_reviews("asc")
    elsif params[:sort] == "desc_reviews"
      number_of_reviews("desc")
    else
      all
    end
  end

  def avg_rating
    reviews.average(:rating)
  end

  def total_reviews
    reviews.count
  end

  def top_reviews(n = 1)
    reviews.order("reviews.rating desc").limit(n)
  end

  def bottom_three_reviews
    reviews.order(:rating).limit(3)
  end
end

app/models/book_author.rb
class BookAuthor < ApplicationRecord
  belongs_to :book, dependent: :destroy
  belongs_to :author
end

app/models/review.rb
class Review < ApplicationRecord
  validates_presence_of :title, :description, :rating

  belongs_to :book
  belongs_to :user

  def self.sorting(direction)
    order("created_at #{direction}")
  end

  validates :user, uniqueness: { scope: :book,
    message: "You already reviewed this book"
  }
end

app/models/user.rb
class User < ApplicationRecord
  validates_presence_of :name

  has_many :reviews, dependent: :destroy

  def review_count
    reviews.count
  end

  def self.top_users
    self.select("users.*, reviews.count AS total_reviews")
        .joins(:reviews)
        .group("users.id")
        .order("total_reviews desc")
        .limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def show
    @author = Author.find(params[:id])
  end

  def destroy
    Author.destroy(params[:id])
    redirect_to books_path
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.sort(params)
    @highest_books = Book.highest_rated_books
    @lowest_books = Book.lowest_rated_books
    @top_users = User.top_users
  end

  def new
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @authors = @book.authors
    @top_reviews = @book.top_reviews(3)
    @bottom_reviews = @book.bottom_three_reviews
  end

  def create
    book = Book.create(book_params)
    author_array = params[:book]["authors"].split(",")
    author_array.each do |author|
      book.authors << Author.find_or_create_by(:name => author.strip)
    end
    redirect_to book_path(book)
  end

  def destroy
    Book.destroy(params[:id])
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :pages, :year)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end 
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @book = Book.find(params[:book_id])
    @review = Review.new
  end
  def create
    @book = Book.find(params[:book_id])
    user_name = params[:review]["username"].titleize
    user = User.find_or_create_by(:name => user_name)
    @review = user.reviews.create(review_params)
    @book.reviews << @review
    if @review.persisted?
      redirect_to book_path(@book)
    else
      render :new
    end
  end

  def destroy
    user = Review.find(params[:id]).user_id
    Review.destroy(params[:id])
    redirect_to user_path(user)
  end

  private

  def review_params
    params.require(:review).permit(:title, :description, :rating)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @reviews = @user.reviews.sorting(params[:sort])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authors/show.html.erb
<div class="view">
  <h3 class="author-header"><%= @author.name %></h3><br/>

  <%= link_to "Delete Author", author_path(@author), method: :delete, data: { confirm: 'Are you sure you want to delete this?' } %>
  <section class="flex-box">

  <% @author.books.each do |book| %>
    <article class="author-book">
      <p><%= link_to "#{book.title}", book_path(book) %></p>
      <p>Pages: <%= book.pages %></p>
      <p>Year: <%= book.year %></p>
      <section class="top_review">
        Top Review:
        <% if book.top_reviews.first != nil %>
          <p><%= link_to "#{book.top_reviews.first.user.name}", user_path(book.top_reviews.first.user) %> ||
          <%= book.top_reviews.first.title %> ||
          Rating: <%= book.top_reviews.first.rating %></p>
        <% end %>
      </section>
    </article>
  <% end  %>

  </section>
</div>

app/views/books/index.html.erb
<a href="/books/new" class="new-book">Create a new book!</a>

<section class="dropdown">
    <button class="dropbtn">Sort</button>
    <div class="dropdown-content">
      <%= link_to "Rating: Lowest to Highest", books_path(sort: "asc_rating"), { :class=> "sort-link" } %><br/>
      <%= link_to "Rating: Highest to Lowest", books_path(sort: "desc_rating"), { :class=> "sort-link" } %><br/>
      <%= link_to "Number of Pages: Lowest to Highest", books_path(sort: "asc_pages"), { :class=> "sort-link" } %><br/>
      <%= link_to "Number of Pages: Highest to Lowest", books_path(sort: "desc_pages"), { :class=> "sort-link" } %><br/>
      <%= link_to "Number of Reviews: Lowest to Highest", books_path(sort: "asc_reviews"), { :class=> "sort-link" } %><br/>
      <%= link_to "Number of Reviews: Highest to Lowest", books_path(sort: "desc_reviews"), { :class=> "sort-link" } %><br/>
    </div>
</section>
<br/>

<div class="view">

  <section class="stats-box">
    <article class="highest_rated_books">
      <h4>Highest Rated Books</h4>
      <% @highest_books.each do |book|%>
       <p class="book_rating"><%= link_to "#{book.title}", book_path(book) %>: <%= book.avg_rating.round(2) %></p>
      <% end %>
    </article>

    <article class="lowest_rated_books">
      <h4>Lowest Rated Books</h4>
      <% @lowest_books.each do |book|%>
       <p class="book_rating"><%= link_to "#{book.title}", book_path(book) %>: <%= book.avg_rating.round(2) %></p>
      <% end %>
    </article>

    <article class="top_users">
      <h4>Top Users</h4>
      <% @top_users.each do |user|%>
       <p><%= link_to "#{user.name}", user_path(user) %> with <%= user.total_reviews %> reviews.</p>
      <% end %>
    </article>
  </section>

  <section class="flex-box">
    <% @books.each do |book| %>
      <article class="book book-box">
        <p>Title: <%= link_to "#{book.title}", book_path(book) %></p>
        <p>Pages: <%= book.pages  %></p>
        <p>Year: <%= book.year  %></p>
        <div id="book_<%= book.id %>">
          <% if book.avg_rating != nil  %>
          <p>Average Rating:<%= book.avg_rating.round(2) %></p>
          <% end %>
          <p>Total Reviews : <%= book.total_reviews %></p>
          <% book.authors.each do |author| %>
            Author(s): <%= link_to "#{author.name}", author_path(author) %>
          <% end %>
        </div>
      </article>
    <% end %>
  </section>

</div

app/views/books/new.html.erb
<div class="view">

  <%= form_for @book do |f| %>
    <p class="form-lines"><%= f.label :title %>
    <div class="form-fields"><%= f.text_field :title %></p></div>
    <p class="form-lines"><%= f.label :pages %>
    <div class="form-fields"><%= f.number_field :pages %></p></div>
    <p class="form-lines"><%= f.label :year %>
    <div class="form-fields"><%= f.number_field :year %></p></div>
    <p class="form-lines"><%= f.label :authors %>
    <div class="form-fields"><%= f.text_field :authors, :value => ""  %></p></div>
    <p class="form-lines"><%= f.submit %></p>
  <% end %>

</div>

app/views/books/show.html.erb
<div class="view">

  <section class="book-show-info">
    <p>Title: <%= @book.title %></p>
    <p>Pages: <%= @book.pages %></p>
    <p>Year: <%= @book.year %></p>
    <p>Author(s): <% @authors.each do |author| %>
      <%= link_to "#{author.name}", author_path(author) %>
    <% end %></p>
  </section>
  <br/>
  <h3 class="book-show-header">Reviews:</h3>
  <div class="add-review">
    <%= link_to "Add Review", new_book_review_path(@book) %>
  </div>

  <%= link_to "Delete this Book", book_path(@book), method: :delete, data: { confirm: 'Are you sure you want to delete this?' } %>

  <section class="book-show-stats">
    <article class="avg-rating">
      <h4>Average Rating:</h4>
      <% if @book.avg_rating != nil  %>
        <p><%= @book.avg_rating.round(2) %></p>
      <% end %>
    </article>

    <article class="top-reviews">
      <h4>Top Reviews</h4>
      <% @top_reviews.each do |review| %>
        User: <%= link_to "#{review.user.name}", user_path(review.user.id) %> |
        Title: <%= review.title %> |
        Rating: <%= review.rating %> ||
        <br/>
      <% end %>
    </article>

    <article class="bottom-reviews">
      <h4>Worst Reviews</h4>
      <% @bottom_reviews.each do |review| %>
        User: <%= link_to "#{review.user.name}", user_path(review.user.id) %> |
        Title: <%= review.title %> |
        Rating: <%= review.rating %> ||
        <br/>
      <% end %>
    </article>
  </section>

  <section class="book-reviews-box">
      <% @book.reviews.each do |review|%>
        <article class="review-box">
          <p><%= link_to "#{review.user.name}", user_path(review.user.id) %></p>
          <p><%= review.title %></p>
          <p><%= review.description %></p>
          <p><%= review.rating %></p>
        </article>
      <% end  %>
  </section>

</div>

app/views/home/index.html.erb
<div class="view">
  <h2 class="welcome">Welcome to Book Club!</h2>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookClub</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://necolas.github.io/normalize.css/latest/normalize.css" title="css" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Ubuntu:400,700" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="grid-container">
    <nav class="navbar">
      <a href="/" class="nav-link">Home</a>
      <a href="/books" class="nav-link">Books</a>
    </nav>
      <%= yield %>
  </body>
</html>

app/views/reviews/new.html.erb
<div class="view">

  <%= form_for [@book,@review] do |f| %>
    <% if @review.errors.any? %>
      <% @review.errors.full_messages.each do |msg| %>
        <%= msg %>
      <% end %>
    <% end %>
    <p class="form-lines"><%= f.label :title %></p>
    <div class="form-lines"><%= f.text_field :title %></div><br/>
    <p class="form-lines"><%= f.label :username %></p>
    <div class="form-lines"><%= f.text_field :username, :value => "" %></div><br/>
    <p class="form-lines"><%= f.label :rating %></p>
    <div class="form-lines"><%= f.select :rating, [[1,1], [2,2], [3,3], [4,4], [5,5]] %></div><br/>
    <p class="form-lines"><%= f.label :description %></p>
    <div class="form-lines"><%= f.text_field :description %></div><br/>
    <p class="form-lines"><%= f.submit %></p><br/>
  <% end %>

</div>

app/views/users/show.html.erb
<div class="view">

  <h1 class="user-review-header"><%= @user.name %></h1>

  <h4 class="user-review-header">My reviews:</h4>
  <section class="user-reviews-box">
    <article class="review-sort-links">
      <p><%= link_to "Newest First", user_path(sort: "desc") %></p>
      <p><%= link_to "Oldest First", user_path(sort: "asc") %></p>
    </article>
      <% @reviews.each do |review| %>
      <article class="review-box" id="review_<%="#{review.id}" %>">
        <p>Title: <%= review.title %></p>
        <p>Book: <%= link_to "#{review.book.title}", book_path(review.book) %></p>
        <p>Rating: <%= review.rating %></p>
        <p><%= review.description %></p>
        <%= link_to "Delete Review", book_review_path(review.book, review), method: :delete, data: { confirm: 'Are you sure you want to delete this?' } %>
        </article>
      <% end %>
  </section>

</div>